### PR TITLE
FIX : foreign keys constraints #7

### LINKED ISSUE #7: FIX : add multi column foreign key contraints
# Issue
The issue #3 may reference missing columns. 

# Analyze
Columns with imported key(s) constraint(s) are generated as a ManyToOne association. 
But, composite foreign key constraints are not managed, so the ManyToOne association is missing.
But the "uniqueConstraint" of @Table annotation may contains these missing columns. 

# Solution
Manage foreign key without restriction:
- generate all columns
- @ManyToOne annotation will generated with the insertable=false and updatable=false

# Additionnal 
The @Data may contains stackoverflow exception (https://stackoverflow.com/questions/17445657/hibernate-onetomany-java-lang-stackoverflowerror)
- Use @Setter and @Getter

### PR DESCRIPTION
**Pull request by gbusnot**

### CODE REVIEW

File: src/main/java/fr/pierrickrouxel/jpaentitygenerator/EntityGenerator.java [hunk 1]
```diff
@@ -239,48 +237,69 @@ public static FieldSpec getField(Column column, String className, List<Index> in
...
+        .map(o -> getManyToOneField(o.getKey(), o.getValue(), columns, classNameRules))
         .collect(Collectors.toList());
   }
 
   /**
    * Generates @ManyToOne annotated field.
    *
    * @param tableName      The table name
-   * @param importedKey    The imported key
+   * @param importedKeys   The imported key
```
Comment (pierrickrouxel) [inline src/main/java/fr/pierrickrouxel/jpaentitygenerator/EntityGenerator.java]: The javadoc is not up to date

File: src/main/java/fr/pierrickrouxel/jpaentitygenerator/EntityGenerator.java [hunk 2]
```diff
@@ -239,48 +237,69 @@ public static FieldSpec getField(Column column, String className, List<Index> in
...
-        .addAnnotation(getJoinColumnAnnotation(importedKey, columns))
+        .addAnnotation(getJoinColumnAnnotation(importedKeys, columns))
         .build();
   }
 
   /**
    * Generates @JoinColumn annotation.
    *
-   * @param importedKey The imported key
+   * @param importedKeys The imported key
```
Comment (pierrickrouxel) [inline src/main/java/fr/pierrickrouxel/jpaentitygenerator/EntityGenerator.java]: The javadoc is not up to date

File: src/test/java/fr/pierrickrouxel/jpaentitygenerator/EntityGeneratorTest.java [hunk 3]
```diff
@@ -77,8 +76,8 @@ public void testGetClassUniqueConstaint() {
     assertThat(entity).contains("@Table(\n" +
       "    name = \"\\\"ARTICLE_TAG\\\"\",\n" +
       "    uniqueConstraints = {\n" +
-      "        @UniqueConstraint(name = \"U_ART_PLV\", columnNames = {\"\\\"articleId\\\"\", \"\\\"plvId\\\"\"}),\n" +
-      "        @UniqueConstraint(name = \"U_ART_TAG\", columnNames = {\"\\\"articleId\\\"\", \"\\\"tagId\\\"\"})\n" +
+      "        @UniqueConstraint(name = \"U_ART_PLV\", columnNames = {\"\\\"ARTICLE_ID\\\"\", \"\\\"PLV_ID\\\"\"}),\n" +
```
Comment (pierrickrouxel) [inline src/test/java/fr/pierrickrouxel/jpaentitygenerator/EntityGeneratorTest.java:79]: Can you provide a more generic example as the project is open sourced

File: src/test/java/fr/pierrickrouxel/jpaentitygenerator/TestDatabase.java [hunk 4]
```diff
@@ -59,7 +59,32 @@ public static void init() throws SQLException {
           ") REFERENCES something_tmp (" +
           "identifier, expiration_timestamp" +
           ")").execute();
+      conn.prepareStatement("CREATE TABLE IF NOT EXISTS vte_ent (" +
```
Comment (pierrickrouxel) [inline src/test/java/fr/pierrickrouxel/jpaentitygenerator/TestDatabase.java]: Can you provide a more generic example as the project is open sourced

File: src/test/java/fr/pierrickrouxel/jpaentitygenerator/metadata/TableMetaDataFetcherTest.java [hunk 5]
```diff
@@ -22,7 +22,7 @@ public static void setupDatabase() throws SQLException {
   @Test
   public void testGetTableNames() throws SQLException {
     var tableNames = fetcher.getTableNames();
-    assertThat(tableNames).hasSameElementsAs(List.of("BLOG", "ARTICLE", "TAG", "ARTICLE_TAG", "SOMETHING_TMP", "SOMETHING2_TMP"));
+    assertThat(tableNames).hasSameElementsAs(List.of("BLOG", "ARTICLE", "TAG", "ARTICLE_TAG", "SOMETHING_TMP", "SOMETHING2_TMP","VTE_ENT","VTE_LIG","VTE_NOM"));
```
Comment (pierrickrouxel) [inline src/test/java/fr/pierrickrouxel/jpaentitygenerator/metadata/TableMetaDataFetcherTest.java]: Can you provide a more generic example as the project is open sourced

**Review by pierrickrouxel — CHANGES_REQUESTED** [review]
